### ISSUE TITLE
Use StreamResponse from worker-tools with nhttp, without blocking further requests

### ISSUE THREAD

**Issue by jacorall** [nhttp/nhttp#24]
I'm trying to use the StreamResponder from worker-tools (https://workers.tools/) with nhttp, but it blocks any further requests.

My aim, i the end, is to have an elegant, easy, short way to stream messages to the browser using Server Sent Events (SSE), when I change a global variable or use BroadcastChannel (that I'm also struggling with) to send a new message. I specifically want to use SSE and not web-sockets.

This is example code that I use for testing:
```
import nhttp from "https://deno.land/x/nhttp/mod.ts";
import * as shed from 'https://ghuc.cc/worker-tools/shed/index.ts'
import staticFiles from 'https://deno.land/x/static_files/mod.ts';

const app = nhttp();
app.use(staticFiles('public'));

const message = 'Hi there';

async function* sse() {
   while (true) {
      await new Promise(r => setTimeout(r, 1000));
      yield `data: ${message}\n\n`;
   }
}

app.get('/sse', async (rev) => {
   console.log('connected')
   rev.respondWith(new shed.StreamResponse(sse(), {
      status: 200,
      headers: new Headers({
         'Connection': 'Keep-Alive',
         'Content-Type': 'text/event-stream',
         'Cache-Control': 'no-cache',
         'Keep-Alive': `timeout=${Number.MAX_SAFE_INTEGER}`,
      })
   }))
});

const options = {
   port: 443,
   certFile: "/etc/letsencrypt/live/api.mytest.com/fullchain.pem",
   keyFile: "/etc/letsencrypt/live/api.mytest.com/privkey.pem",
   alpnProtocols: ["h2", "http/1.1"]
}

app.listen(options, (err, opts) => {
   if (err) throw err;
   console.log("Running on server " + opts.port);
});
```
I then call this from the browser/html with:
```
      const evtSource = new EventSource('sse');
      evtSource.onmessage = async (event) => {
         console.log(event)
      };
```

**Comment by jacorall** [comment]
I also tried a different approach, that you suggested a while back, by extending the 'Response':
```
import nhttp from "https://deno.land/x/nhttp/mod.ts";
import staticFiles from 'https://deno.land/x/static_files/mod.ts';

const app = nhttp();
app.use(staticFiles('public'));

let message = 'Hi there';

app.post('/sendmessage'), async (rev) => {
   rev.message
}

app.get("/sse", async ({ respondWith }) => {
   try {
      const onClose = (error) => {
         console.log(error.message);
      };
      const onComplete = () => {
         console.log('Complete Task');
      };
      respondWith(new SSEResponse(message, { onClose, onComplete }));
   } catch (err) {
      console.log(err)
   }
});

const options = {
   port: 443,
   certFile: "/etc/letsencrypt/live/api.mytest.com/fullchain.pem",
   keyFile: "/etc/letsencrypt/live/api.mytest.com/privkey.pem",
   alpnProtocols: ["h2", "http/1.1"]
}

app.listen(options, (err, opts) => {
   if (err) throw err;
   console.log("Running on server " + opts.port);
});

class SSEResponse extends Response {
   constructor(message, opts) {
      let timer = opts.timer || 500;
      let newm, oldm, interval;

      opts.headers = new Headers({
         Connection: 'Keep-Alive',
         'Content-Type': 'text/event-stream',
         'Cache-Control': 'no-cache',
         'Keep-Alive': `timeout=${Number.MAX_SAFE_INTEGER}`,
      });

      const body = new ReadableStream({
         start(controller) {
            interval = setInterval(() => {
               newm = JSON.stringify(message);
               if (newm !== oldm) {
                  controller.enqueue(new TextEncoder().encode(`data: ${newm}}\n\n`));
                  oldm = newm;
               }
            }, timer);
         },
         cancel(error) {
            opts.onClose(error);
            clearInterval(interval);
         },
      });
      super(body, opts);
   }
}
```
This gives the following error, when connecting to the '/sse' event source:
```
TypeError: Cannot set properties of undefined (setting 'Symbol(res)')
    at respondWith (https://deno.land/x/nhttp@1.2.19/src/request_event.ts:127:21)
    at file:///root/flyairlink/example.js:21:7
    at next (https://deno.land/x/nhttp@1.2.19/src/nhttp.ts:278:67)
    at https://deno.land/x/static_files@1.1.6/mod.ts:84:14
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async onAsyncRes (https://deno.land/x/nhttp@1.2.19/src/nhttp_util.ts:23:57)
    at async Object.respondWith (ext:deno_http/01_http.js:202:14)
    at async HttpServer.handleHttp (https://deno.land/x/nhttp@1.2.19/src/nhttp_util.ts:86:11)
```

**Comment by jacorall** [comment]
When make the example.js file simpler by not using the  static_files module:
```
import nhttp from "https://deno.land/x/nhttp/mod.ts";

const app = nhttp();

let message = 'Hi there';

app.post('/sendmessage'), async (rev) => {
   message = rev.body.message;
}

app.get("/sse", async ({ respondWith }) => {
   try {
      const onClose = (error) => {
         console.log(error.message);
      };
      const onComplete = () => {
         console.log('Complete Task');
      };
      respondWith(new SSEResponse(message, { onClose, onComplete }));
   } catch (err) {
      console.log(err)
   }
});

const options = {
   port: 443,
   certFile: "/etc/letsencrypt/live/api.mytest.com/fullchain.pem",
   keyFile: "/etc/letsencrypt/live/api.mytest.com/privkey.pem",
   alpnProtocols: ["h2", "http/1.1"]
}

app.listen(options, (err, opts) => {
   if (err) throw err;
   console.log("Running on server " + opts.port);
});

class SSEResponse extends Response {
   constructor(message, opts) {
      let timer = opts.timer || 500;
      let newm, oldm, interval;

      opts.headers = new Headers({
         Connection: 'Keep-Alive',
         'Content-Type': 'text/event-stream',
         'Cache-Control': 'no-cache',
         'Keep-Alive': `timeout=${Number.MAX_SAFE_INTEGER}`,
      });

      const body = new ReadableStream({
         start(controller) {
            interval = setInterval(() => {
               newm = JSON.stringify(message);
               if (newm !== oldm) {
                  controller.enqueue(new TextEncoder().encode(`data: ${newm}}\n\n`));
                  oldm = newm;
               }
            }, timer);
         },
         cancel(error) {
            opts.onClose(error);
            clearInterval(interval);
         },
      });
      super(body, opts);
   }
}
```
I then get the following error:
```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'length')
          this.route[key] = fns[0].length ? fns : fns[0];
                                   ^
    at invoke (https://deno.land/x/nhttp@1.2.19/src/nhttp.ts:168:36)
    at NHttp.on (https://deno.land/x/nhttp@1.2.19/src/nhttp.ts:174:10)
    at NHttp.post (https://deno.land/x/nhttp@1.2.19/src/router.ts:177:17)
    at file:///root/flyairlink/example.js:7:5
```

**Comment by herudi** [comment]
this code is wrong. 
```ts
app.post('/sendmessage'), async (rev) => {
   message = rev.body.message;
}
```
change with this
```ts
app.post('/sendmessage', async (rev) => {
   message = rev.body.message;
});
```
